// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import path from 'path'

export default defineConfig({
  schema: path.join('prisma'),
  migrations: {
    path: "migrate/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
